Added Network entitlements for MacOS client to access the network
brainwo/yatta pull request #16
Opened 2023-07-12 02:40 UTC by asif4318

2023-07-12 03:34 UTC, brainwo requested changes
- Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.
- Remove unnecessary template test file too

2023-07-12 03:34 UTC, brainwo commented on test/widget_test.dart
This widget test is unnecessary and not reflect the app intended behavior.

2023-07-12 03:34 UTC, brainwo commented on windows/.gitignore
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/CMakeLists.txt
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/flutter/CMakeLists.txt
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/flutter/generated_plugin_registrant.cc
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/flutter/generated_plugin_registrant.h
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/flutter/generated_plugins.cmake
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/runner/CMakeLists.txt
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/runner/Runner.rc
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/runner/flutter_window.cpp
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/runner/flutter_window.h
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/runner/main.cpp
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/runner/resource.h
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/runner/resources/app_icon.ico
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/runner/runner.exe.manifest
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/runner/utils.cpp
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/runner/utils.h
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 03:34 UTC, brainwo commented on windows/runner/win32_window.cpp
Remove the entire windows folder, and put it to a separate PR if you wanted to support Windows, currently I have no interest in supporting Windows because I'm not able to test and tweak it to better suit Windows needs.

2023-07-12 14:08 UTC, asif4318 commented
Removed Windows support for now

2024-04-14 03:52 UTC, brainwo commented
No plan for supporting macOS yet. I appreciate this pull request, however I don't think I will merge this, unless it adds more than just support for compiling to macOS.

2024-04-14 03:52 UTC, closed without merging